version: '3'
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
       - db_data:/var/lib/sqlite3
    restart: always


  oc_lettings:
    build: .
    command: python3 manage.py runserver localhost:8000
    depends_on:
       - db
    image: mraka/oc-lettings:latest
    ports:
       - "8000:80"
    
    restart: always