version: '3.9'
services:
  db:
    image: nouchka/sqlite3:latest
    ports:
      - 6379:6379

  oc_lettings:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    image: mraka/oc-lettings:latest
    ports:
      - "8000:8000"
    restart: always

  
  