version: '3.9'
services:
  db:
    image: nouchka/sqlite3:latest
    ports:
      - 5000:5000

  oc_lettings:
    build: .
    command: python3 manage.py runserver
    depends_on:
      - db
    image: mraka/oc-lettings:latest
    ports:
      - "5000:5000"
    volumes:
      -.:/app
    restart: always

  
  