# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build_and_test: # this can be any name you choose
    executor: python/default # use the default executor defined within the orb
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      
      - run:
          name: Run tests
          command: python -m pytest
      - run:
          name: Linting
          working_directory: ~/workspace/src
          command: |
            mkdir -p test-reports/flake8
            flake8 . --output-file=test-reports/flake8/flake8.txt
          
     
  build:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run: echo "DOCKERHUB_PASSWORD" | docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
          
      - run:  docker build -t oc-lettings:$CIRCLE_SHA1 .
      - run:  docker tag oc-lettings:$CIRCLE_SHA1 $USERNAME/oc-lettings
      - run:  docker push  $USERNAME/oc-lettings

  deploy:
    docker:
      - image: cimg/python:3.10.5
    steps:
       - checkout
       - run:
           name: Deploy Main to Heroku
           command: |
             git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  
  sentry-release:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - run:
          name: Install Sentry cli
          command: curl -sL https://sentry.io/get-cli/ | SENTRY_CLI_VERSION="2.4.1" bash
      - run:
          name: Deploy new release
          command: |
            sentry-cli releases -p $SENTRY_PROJECT new $CIRCLE_SHA1
            sentry-cli releases -p $SENTRY_PROJECT set-commits --auto $CIRCLE_SHA1
            sentry-cli releases -p $SENTRY_PROJECT finalize $CIRCLE_SHA1
  
  
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  Python-OC-Lettings-workflow:
    jobs:
      - build_and_test
      - build:
          requires:
             - build_and_test
          filters:
            branches:
              only: master 
      - deploy:
          requires:
             - build_and_test
             - build # only run deploy-via-git job if the build job has completed
          filters:
             branches:
               only: master 
      - sentry-release:
          requires:
             - build_and_test
             - build 
             - deploy # only run deploy-via-git job if the build job has completed
          filters:
             branches:
               only: master 